Allow processing of kinesis events to fallback top individual processing
flowcommerce/lib-event pull request #652
Opened 2022-07-08 19:01 UTC by jlogeart

This change introduces the ability to reprocess events individually in case the batch processing failed.

It prevents events that are following a failing one to be discarded. 
A common use case is for instance processing a batch and shutting down before checkpointing. When consumption restarts, a new batch is taken from the queue, potentially with new events that have not yet been processed and the whole batch fails because of duplicate id, leading to the newly taken events to be discarded instead of processed.

Note this change is not source compatible with the previous version and will require careful deploy.

2022-08-02 21:40 UTC, benwaffle requested changes

2022-08-02 21:40 UTC, benwaffle commented on app/io/flow/event/v2/KinesisStyle.scala
> +                s"$size records are not retried individually are skipped. " +
```suggestion
                s"$size records are not retried individually, they are skipped. " +
```

2022-08-02 21:40 UTC, benwaffle commented on app/io/flow/event/v2/KinesisStyle.scala
> +                s"Sequence numbers: ${records.map(_.sequenceNumber).mkString(", ")}", e)
You should use `withKeyValue` to output the sequence numbers

2022-08-02 21:40 UTC, benwaffle commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +      val consumed = new AtomicBoolean(false)
If you're looking for thread safety, I think you need to get() failed and set() consumed in a single atomic transaction

2022-08-02 21:40 UTC, benwaffle commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +        // 3 as a batch, 2 individually
should this be 0 individually?

2022-08-02 21:40 UTC, benwaffle commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +            triesBatch1.incrementAndGet()
this test is confusing to read. shouldn't you be incrementing `tries2`?

is there a cleaner way to write it? something in this style?
```
recs.map(_.eventId) match {
  case Seq(e1, e2) => tries.batch.incrementAndGet(); throw new Exception("batch failed")
  case Seq(e1) => tries.e1.individual.incrementAndGet()
  case Seq(e2) => tries.e2.individual.incrementAndGet()
}
```

2022-08-02 21:40 UTC, benwaffle commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +      config.set("development_workstation.lib.event.test.v0.test_event.json.enableIndividualProcessingFallback", "false")
if the test is identical except for this line, can we move the test into a function?

2022-08-02 21:41 UTC, benwaffle commented
Other questions:
1. Do kinesis event consumers fail a lot? I thought they usually just insert into a DB queue
2. Where is the source incompatibility?

2022-08-03 01:01 UTC, jlogeart commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +      val consumed = new AtomicBoolean(false)
I am mostly interested in the `volatile` portion embedded in the `Atomic` such that the memory is properly flused between threads upon assignments.

I could have used `@volatile` too.

2023-04-26 20:36 UTC, jlogeart commented
You can search for `"num_skipped_records"` in our logs to find occurrences: https://service.us2.sumologic.com/ui/#/search/create?id=ZaIy2nQ6GVQqB9IIe05AfEU2scEDiYj7VbvbE1es

2023-04-28 22:04 UTC, jlogeart commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +        // 3 as a batch, 2 individually
No, it is retried twice (1 retry) before fully failing.

2023-04-28 22:04 UTC, jlogeart commented on test/io/flow/event/v2/IntegrationQueueSpec.scala
> +            triesBatch1.incrementAndGet()
Good suggestion

2023-05-01 20:34 UTC, benwaffle approved these changes

2023-05-25 19:42 UTC, merged